//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemSerDar.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemEXEntities : DbContext
    {
        private static DemEXEntities _context;

        public static DemEXEntities GetContext()
        {
            if (_context == null)
                _context = new DemEXEntities();
            return _context;
        }

        public DemEXEntities()
            : base("name=DemEXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Material_type_import> Material_type_import { get; set; }
        public virtual DbSet<Partner_products_import> Partner_products_import { get; set; }
        public virtual DbSet<Partners_import> Partners_import { get; set; }
        public virtual DbSet<Product_type_import> Product_type_import { get; set; }
        public virtual DbSet<Products_import> Products_import { get; set; }
        public virtual DbSet<TypePartner> TypePartner { get; set; }
    }
}
