//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemSerDar.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner_products_import
    {
        public int ID { get; set; }
        public Nullable<int> IDNameProduct { get; set; }
        public Nullable<int> IDNamePartner { get; set; }
        public string CountProduct { get; set; }
        public Nullable<System.DateTime> DateSale { get; set; }
    
        public virtual Partners_import Partners_import { get; set; }
        public virtual Products_import Products_import { get; set; }
    }
}
